export const VEHICLESFAKEDATA = [
    {
        name: "Corsário",
        modelo: "Cruzeiro de passeio",
        noise: 60,
        status: "Aprovado" as const,
        image: require("@/assets/images/vehicles/Cruise.png"),
        place: "Praia da Mococa",
        data: "26/05/24",
    },
    {
        name: "Azimut 60",
        modelo: "Iate de luxo",
        noise: 70,
        status: "Pendente" as const,
        image: require("@/assets/images/vehicles/Azimut-60.png"),
        place: "Praia da Tabatinga",
        data: "12/01/22",
    },
    {
        name: "Lagoon 450",
        modelo: "Catamarã",
        noise: 90,
        status: "Reprovado" as const,
        image: require("@/assets/images/vehicles/Lagoon.jpg"),
        place: "Praia da Maranduba",
        data: "02/03/23",
    },
    {
        name: "Cigarette Racing",
        modelo: "Lancha de corrida",
        noise: 105,
        status: "Reprovado" as const,
        image: require("@/assets/images/vehicles/Cigarette.jpg"),
        place: "Fernando de Noronha",
        data: "31/07/21",
    },
    {
        name: "Viking 55",
        modelo: "Barco de pesca",
        noise: 95,
        status: "Aprovado" as const,
        image: require("@/assets/images/vehicles/Viking-55.jpg"),
        place: "Praia da Almada",
        data: "23/11/22",
    },
];